image: monachus/hugo

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  HUGO_BASEURL: https://ipspace.gitlab.io/slovenia-hiking
  TZ: Europe/Berlin

pages:
  script:
  - hugo version
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master
