---
- repo: local
  hooks:
  - id: yamllint
    name: yamllint
    description: This hook runs yamllint.
    entry: yamllint
    language: python
    types: [file, yaml]

  - id: md-check
    name: Check Markdown frontmatter and LOCALHOST links
    entry: tools/md-check.py
    language: script
    types: [file, markdown]

  - id: hike-sync
    name: Sync hike data
    entry: tools/hike-precommit.sh
    language: script
    files: "/hikes/"
