name = "ipspace"
license = "MIT"
licenselink = "https://github.com/jbub/ghostwriter/blob/master/LICENSE.md"
description = "A fork of the ghostwriter theme."
tags = ["blog", "technical", "personal"]
features = ["blog", "technical", "personal"]

[author]
    name = "Ivan Pepelnjak"
    homepage = "https://github.com/ipspace"

[original]
    name = "Juraj Bubniak"
    homepage = "https://github.com/jbub"
