#!/usr/bin/env python3

import sys
import os
import argparse
from PIL import Image, ImageDraw, ImageFont

import cm.images
import datetime

def parse_cli():
  parser = argparse.ArgumentParser(description='Import pictures into Hiking directory')
  parser.add_argument('pics', nargs='*',action='store',help='Pictures to import')
  return parser.parse_args()

txt = "{{<gallery>}}\n"
for img in args.pics:
  txt = txt + '{{<figure src="%s">}}\n' % os.path.basename(img)
txt = txt + "{{</gallery>}}\n"
  if args.prefix:
    if args.prefix in img:
      print("%s already imported, skipping" % img)
      continue

  try:
    print("Importing %s" % img)
    cm.images.watermark(img,author=get_author)
  except:
    print("Failed to import picture(s) %s\n%s" % (img,str(sys.exc_info()[1])))
    break

  if args.prefix or args.renumber:
    pic_dir  = os.path.dirname(img)
    pic_name = os.path.basename(img)
    if args.prefix:
      new_name = args.prefix + "-" + pic_name.replace(" ","-").lower()
    if args.renumber:
      new_name = get_pic_id(pic_dir,"M_")

    new_name.replace(".jpeg",".jpg")
    print("Renaming %s to %s" % (pic_name,new_name))
    if pic_dir:
      pic_dir = pic_dir + "/"
    os.rename(img,pic_dir+new_name)
